/* Home page text content */
export const welcomeText = "The Sandra Day O'Connor Computer Science Club is a student-led club meant to foster hands on STEM experience through hackathons and hands on projects. We are open to all students, regardless of experience level, and we encourage you to join us in our mission to make computer science accessible and fun for everyone.";
export const clickText = "Click on the links below to learn more about our projects and how you can get involved.";
export const handsOnText = "We provide hands-on experience through various projects and hackathons, allowing students to apply their skills in real-world scenarios. Our projects range from web development to robotics, ensuring there's something for everyone.";
export const ocHacksText = "OCHacks is our annual student-led hackathon event where students from around the district come together to develop real world applications of software engineering. Through OCHacks, we aim to help develop real-world coding skills and take STEM education outside the classroom.";
export const educationText = "We also focus on educational initiatives, providing resources to students of all experience levels. We want to encourage new learners and even experienced ones to constantly learn and expand their knowledge in computer science."

/* HandsOn page text content */
export const handsOnDescriptionText = "As a part of the OC Computer Science Club, we encourage students to engage in hands-on projects in hackathons at a national level. See some of our previous projects below!"
export const cacText = "The Congressional App Challenge is a nationwide competition that encourages students to learn coding and create their own apps. Participants can work individually or in teams to develop an app that addresses a problem or provides a solution. The challenge is open to middle and high school students, and winners are recognized by their local representatives in Congress. For our submission, we created an app focused on teen mental health awareness. Our app was a short mental health quiz that provided a tailored response based on answeres to peer-reviewed questions. See the qr code and images below for more information.";
export const mcText = "Mill City Hacks was a locally run hackathon originating from Mill City, Oregon. We submitted a project focused on giving motivation through a quote-a-day idea. See qr code and images below for more information."